### ISSUE TITLE
Picture Organization

### ISSUE THREAD

**Issue by BlakeBouchard** [cs301w01/Skindex#7]
Someone who has a more current knowledge of SQL (ie. someone who's done 291 more recently than me) can explain how [organizing pictures as "albums"](https://github.com/cs301w01/Meat-Loaf/wiki/Use-Case-%234:-Organize-Pictures) would be implemented in SQL. I feel like it has something to do with views, but I am at a loss as to how to elaborate on that.

**Comment by Rstuvi** [comment]
I know how to draw up SQL tables and whatnot... but I've never heard of the term 'album'

**Comment by BlakeBouchard** [comment]
Not as an SQL term, just as an organizational concept. The idea would be that each picture would have one or more "tags" and each tag would be a potential view on that data. A picture would have 0...\* tags, and each tag could be used as a table in itself to act as a view on that data.

**Comment by Rstuvi** [comment]
How I feel it should be done is only have one single table for pictures and their associated data with one entry per picture, then have a second table called tags or something, and only have two columns, one is the ID of a picture corresponding to the ID of a row in the pictures table, and the other will just be a string representing a tag... This will create connections between pictures and tags and will make everything easily queriable. 

First of all, the user should be able to search their pictures just by typing in a search, this will get all the pictures that have any of the words in the search as any of their tags, the pictures that have more tags appearing in the search criteria are obviously more "related" to the search and should appear first.

Second, the user should be able to create albums, and an album is simply a set of tags, basically just saying ONLY pictures that have exactly these tags should be in this album. I like the term "Visual Log" personally... Then when the user takes a picture, they should be given the option, instead of assigning tags to the picture, they should say, I want to put the picture in THIS album, and what that will do is just automatically assign all the appropriate tags required for the picture to be in that album

What do you guys think?

**Comment by Rstuvi** [comment]
This would all be trivial to do using simple SQL queries.
